---
title: "Data Analysis Project, Part 1: Project Proposal"
subtitle: "BIOST 311: Regression Methods in the Health Sciences"
author: "Kelsey Grinde and Brian Williamson"
date: "Spring Quarter 2018; Submit on Canvas by 13 April 2018"
output: pdf_document
---

## Instructions

The goal of the first component of your Data Analysis Project, the *Project Proposal*, is to ensure that you have chosen a dataset and decided on the scientific questions you would like to answer through your analysis.

See the Canvas page for a list of places you can start looking for datasets. The criteria for a dataset are:

1. The dataset must have more than five variables
2. The dataset must have an outcome variable that is continuous, binary, or time-to-event
3. You must be able to pose at least two interesting scientific questions (judged by us) that you can answer using the data

Your final *Proposal* should be a **one page** (single-spaced, 12 point font) Word or .pdf document that contains a brief description of the data, the scientific problem, and the scientific questions that you want to answer.

Please submit on Canvas by 11:59pm on April 13. Only one submission per group. **Do not discuss your project with students outside of your group or post questions about your project on the Canvas discussion board.** But, feel free to ask us any questions in person/over email instead!

This assignment is graded and is worth 5% of your total project grade.  

## Template:

### Title

Make up a title for your proposed study!

### (Brief) Background and Introduction

Provide a brief description of your data to give perspective into the importance of the problem and the situation under study. In particular, why were the data collected? Also, make sure you mention the source of your data: if you found it online, provide the link; otherwise, upload a copy of your dataset to Canvas along with your *Proposal*.

### Scientific Questions

In this section, you should lay out the scientific agenda of your analysis. In particular, you should state both the overall scientific goal and the specific scientific objectives.

Example: a study of smoking and lung function in children

The overall scientific goal is to assess the association between smoking and lung function in children. Specifically, we will address the following questions:

1. Is smoking associated with decreased lung function in children?
2. If there is an association between smoking and decreased lung function, is this effect different in older versus younger children?
