---
title: 'Data Analysis Project, Part 2: SAP'
subtitle: "BIOST 311: Regression Methods in the Health Sciences"
author: "Kelsey Grinde and Brian Williamson"
date: "Spring Quarter 2018; Submit on Canvas by 27 April 2018"
output: pdf_document
---

# Instructions

Statistical Analysis Plans (SAPs) are an integral part of any statistical analysis. In this document, you will outline the statistical analyses you plan to run and any output that you plan to create. SAPs are especially important for reproducibility of your results---the goal is that anyone should be able to exactly re-create your analysis after reading your SAP.

This assignment is limited to **three pages (not including dummy tables and figures)**, and your written text should use at least 12-point font. See the template below for a list of components that need to be included in your final *Statistical Analysis Plan.*

Submit your SAP on Canvas by 11:59pm on April 27. Only one submission per group. **Do not discuss your project with students outside of your group or post questions about your project on the Canvas discussion board.** But, feel free to ask us any questions in person/over email instead!

This assignment is graded and is worth 15% of your total project grade.

# Template and Rubric

## Formatting (0.5 points)

(*Do not include this section in your report.*) 

To receive full credit for this portion of the assignment, you should...

- submit on time
- use 12 point font
- write no more than three pages (not including your variables table or dummy tables/figures)
- include all group member names

## Title (0.5 points)

*Make up a title for your proposed study!*

To receive full credit for this portion of the assignment, your title should...

- be interesting and informative (e.g., allude to your scientific goal)
- not contain any abbreviations

## Background and Introduction (1 point)

*Provide a brief description of your data to give perspective into the importance of the problem and the situation under study. In particular, why were the data collected?*

To receive full credit for this portion of the assignment, your background/introduction should include...

- 1-2 paragraphs of scientific background
    - Set the stage for why this is an interesting overall scientific question to study
    - Why is this an important/relevant outcome to look at?
    - Why is this an important/relevant predictor/exposure to look at?
    - What other variables might be related to your outcome and/or predictor?
- (Brief, 1 paragraph) description of study/data
    - Who (is being studied)? 
    - Where (was the study conducted/are your subjects from)? 
    - When (was the data collected)?
    - Where did you get your data (provide enough detail that someone else could go out and find it)

NOTE: you can re-use what you wrote for your *Project Proposal,* but make sure to address any of the comments we gave you, and you will probably need to add additional detail to address the criteria above


## Scientific Questions (1 point)

*In this section, you should lay out the scientific agenda of your analysis. In particular, you should state both the overall scientific goal and the specific scientific objectives.*

To receive full credit for this portion of the assignment, you should include...

- your overall scientific goal
- at least two specific scientific questions

NOTE: you can re-use what you wrote for your *Project Proposal,* but make sure to address any of the comments we gave you


## Study Design (1 point)

*How were the data collected? How many subjects are in the study? Include all necessary information for interpreting your analysis.*

To receive full credit for this portion of the assignment, you should include...

- who is being studied
- what type of study is this (observational vs experimental; if observational, what type)
- where was this study conducted, where are the subjects from
- when was this study conducted
- how were data collected

NOTE: you will discuss *what* was collected in the "Variables" section


## Statistical Questions (2 points)

*Connect the scientific questions listed above with statistical hypotheses, that you can test using your statistical tools. Make sure to list all variables that you will use in each analysis.*

To receive full credit for this portion of the assignment, you should take each of your (2+) specific scientific questions and re-phrase them as a "statistical question" here. In particular, your statistical question should be a more precise version of your scientific question, which specifies:

- what is the outcome variable
- what is the predictor of interest
- what other variables will you adjust for
- how are you defining association (e.g., difference in means via linear regression, ratio of odds via logisitic regression, ratio of hazards via proportional hazards regression)

## Variables (2 points)

*Create a table which lists EVERY variable in your dataset and provides its name, brief description, classification according to type (e.g., quantitative, categorical, binary), units of measurement, scientific meaning (see below), and role in the analysis (see below). If you are going to create any new variables (e.g., by re-coding a "sex" variable taking on values 1 for male and 2 for female to a binary "female" variable from), please include the new variable in this table as well.*

*Examples of scientific meaning:*

- demographic (e.g., age, sex)
- baseline physiology (e.g., systolic blood pressure)
- baseline disease risk factors
- measures of treatment intervention (in an experiment) or exposure (in an observational study)
- measures of treatment outcome (in an experiment) or exposure effect (in an observational study)

*Examples of role in analysis (note: variables could have more than one, if used in more than one analysis):*

- response (outcome)
- predictor(s) of interest
- variables identifying subgroups to explore (effect modifiers)
- potential confounders
- potential precision variables
- surrogates for the response
- variables that are a result of the predictor of interest
- irrelevant variables

To receive full credit for this portion of the assignment, you should...

- list every variable in your dataset
- provide all pieces of information mentioned above: name, description, type, units, scientific meaning, role in analysis
- organize this information into a table

## Statistical Analysis

### Descriptive Analyses (2 points)

*Describe the descriptive statistics you will compute, how you will compute them, and how you will display your results (figures, tables). Generally, descriptive statistics are used to evaluate and compare subgroups, identify errors in the data, and identify patterns of missing data. Often, these descriptive analyses will support the inferential analyses you report.*

To receive full credit for this portion of the assignment, you should include...

- description of what numerical summaries you will calculate (e.g., mean, standard deviation, proportion, number of missing) for what variables, and within which subgroups (if applicable)
- description of any tables and figures

NOTE: make sure that you think about how you will use descriptive statistics for (1) data cleaning/checking for errors, (2) describing your study subjects (e.g., Table 1), and (3) answering your statistical questions

### Inferential Analyses (2 points)

*Describe the inferential analyses you will run (e.g., linear regression, logisitic regression), along with the estimates (e.g., which coefficients) and any other relevant values (e.g., confidence intervals) that you will interpret and report.*

To receive full credit for this portion of the assignment, you should include...

- a description of the model you will use to address each of your statistical questions
- for each model: what type of regression, what is your outcome, what is your predictor of interest, what variables are you adjusting for
- what numbers will you report/interpret; if this includes a p-value, what are your null and alterative hypotheses and what p-value threshold will you use for calling something "statistically significant"

## Dummy Tables and Figures (1 point)

*Include a sample of the tables and figures you expect to see here. The tables and figures can be empty: just provide a rough sketch of what will be displayed. For example, you might present a figure with a title and axis labels, but no actual data plotted.*

To receive full credit for this portion of the assignment, you should include...

- one dummy table/figure per table/figure mentioned in your Descriptive or Inferential Analyses sections
- any figures should include a title and axis labels
- any tables should include a title and informative row/column names

## Preliminary Analysis (2 points)

*Please run one regression analysis on your dataset. You might run one of the analyses you propose in your* Statistical Analysis *section, or you could just run a simple, unadjusted analysis of your outcome versus the predictor of interest.*

To receive full credit for this portion of the assignment, you should...

- describe what analysis you've run (what type of regression did you use? what was your outcome? your predictor? any other variables included? did you use all your data or just a subset?)
- interpret the relevant results of your analysis (coefficient, confidence interval, p-value)
- upload your R code **and** data to Canvas
